postgresql:
  fullnameOverride: 'postgres'    
  auth:    
    postgresPassword: xpass
    database: identity


kratos:  
  image:
    repository: 'oryd/kratos'   
  kratos:
    autoMigrate: true
    development: false
    config:
      session:
        lifespan: 12h
        cookie:
          name: 'kratos_session'
      dsn: postgres://postgres:xpass@postgres:5432/identity?sslmode=disable
      secrets:
        cookie:
          - 'THE_COOKIE_THAT_SHOULD_BE_CHANGED_ON_PROD'
      log:
        level: debug
        leak_sensitive_values: false
      courier:
        smtp:
          connection_uri: smtp://mail:587
      serve:
        public:
          base_url: /.ory/kratos/public
          cors:
            enabled: false            
        admin:
          base_url: http://kratos-admin
      identity:
        default_schema_id: default
        schemas:
        - id: default
          url: file:///etc/config/identity.default.schema.json        
        
      hashers:
        argon2:
          parallelism: 1
          memory: 128MB
          iterations: 2
          salt_length: 16
          key_length: 16

      selfservice:
        default_browser_return_url: /dashboard
        allowed_return_urls:
          - /dashboard

        methods:
          password:
            enabled: true

        flows:
          error:
            ui_url: /error

          settings:
            ui_url: /settings
            privileged_session_max_age: 15m

          recovery:
            enabled: true
            ui_url: /reset-password

          verification:
            enabled: true
            ui_url: /verify
            after:
              default_browser_return_url: /

          logout:
            after:
              default_browser_return_url: /auth/login

          login:
            ui_url: /auth/login
            lifespan: 10m

          registration:
            lifespan: 10m
            ui_url: /auth/registration
            after:
              password:
                hooks:
                  - hook: session
    identitySchemas:
      'identity.default.schema.json': |
        {
          "$id": "https://schemas.ory.sh/presets/kratos/quickstart/email-password/identity.schema.json",
          "$schema": "http://json-schema.org/draft-07/schema#",
          "title": "Person",
          "type": "object",
          "properties": {
            "traits": {
              "type": "object",
              "properties": {
                "email": {
                  "type": "string",
                  "format": "email",
                  "title": "E-Mail",
                  "minLength": 3,
                  "ory.sh/kratos": {
                    "credentials": {
                      "password": {
                        "identifier": true
                      }
                    },
                    "verification": {
                      "via": "email"
                    },
                    "recovery": {
                      "via": "email"
                    }
                  }
                },
                "name": {
                  "type": "string",
                  "title": "Name"
                }
              },
              "required": ["email"],
              "additionalProperties": false
            }
          }
        }


